// data.js: all rank, branch, tab and palette data. This is the file to edit to change ranks.
// TIERS: the 28 paygrade rows, top to bottom. Every branch "ranks" string must have one entry per tier.
const TIERS = ['FO-5','FO-4','FO-3','FO-2','FO-1','SO-3','SO-2','SO-1','JO-4','JO-3','JO-2','JO-1','MID-1',
  'WO-4','WO-3','WO-2','WO-1','SNCO-3A','SNCO-3','SNCO-2A','SNCO-2','SNCO-1','JNCO-3','JNCO-2','JNCO-1','E-3','E-2','E-1'];

// TIER_GROUPS: heading text shown above certain tier rows in the table.
const TIER_GROUPS = {
  'FO-5':'FLAG OFFICERS // BRANCH APEX', 'FO-3':'FLAG OFFICERS // STRATEGIC COMMAND', 'FO-1':'FLAG OFFICERS // SENIOR COMMAND',
  'SO-3':'SENIOR OFFICERS // OPERATIONAL MANAGEMENT', 'JO-4':'JUNIOR OFFICERS // FIELD EXECUTION',
  'MID-1':'COMMISSIONED ENTRY // CADET OFFICERS', 'WO-4':'WARRANT OFFICERS // TECHNICAL EXPERTISE',
  'SNCO-3A':'SENIOR NON-COMMISSIONED OFFICERS // APEX ENLISTED', 'SNCO-2A':'SENIOR NON-COMMISSIONED OFFICERS // COMPANY LEVEL',
  'JNCO-3':'JUNIOR NON-COMMISSIONED OFFICERS', 'E-3':'ENLISTED // EXPERIENCED', 'E-2':'ENLISTED // STANDARD', 'E-1':'ENLISTED // ENTRY'
};

// FAMILIES: insignia colour palettes, one per branch family (fleet, ground, intel, etc.).
const FAMILIES = {
  fleet:   { bg:'#3b3f63', mark:'#f5b800', note:'Gold triangles on a navy field. A red underline marks command qualification; more triangles and a longer bar mean higher grade.' },
  ground:  { bg:'#2f4033', mark:'#9b0a0a', note:'Red triangles on a dark green field. A gold bar marks field-command qualification; more triangles mean higher grade.' },
  intel:   { bg:'#4b4c50', mark:'#1a1a78', note:'Blue triangles on a grey field. Gold bars above and red bars below mark the senior and special grades.' },
  civil:   { bg:'#1f4650', mark:'#dfe9f6', note:'Ivory triangles on a slate-teal field. A gold bar marks a Charter-confirmed office.' },
  veil:    { bg:'#14161f', mark:'#8d96a8', note:'Silver triangles on a black field. Worn only on internal identity cards, never in public.' },
  support: { bg:'#3a2f28', mark:'#e8832a', note:'Bronze triangles on a brown field. A gold bar marks a certified technical authority.' },
  vigil:   { bg:'#1a1216', mark:'#d9ceb6', note:'Bone triangles on a black-oxblood field. A crimson bar marks the Chapter and the Magister. Every rank, Oblate to Magister, bears the Order\'s own mark: a pale hexagon holding a red slit-pupil eye.' },
  droid:   { bg:'#1b2a36', mark:'#38d6ff', note:'Cyan triangles on a steel field. A cyan bar marks a learning-core certified unit.' },
  police:  { bg:'#1d2b4a', mark:'#8fb8ff', note:'Pale-blue triangles on a midnight field. A gold bar marks senior constabulary authority.' }
};

// BRANCHES: every branch. "ranks" holds 28 names separated by ";" ("-" = no rank at that tier). Other fields feed the dossier text.
const BRANCHES = {

navy: { tab:'fleet', label:'Navy', name:'Confederate Navy', fam:'fleet',
  intro:"The Confederate Navy is the Provincial Authority's principal instrument of force. It descends directly from the Separatist Navy of Admiral Trench: the 9th Fleet that reached Osseriton in 19 BBY is its founding formation. Capital ships are crewed by a small organic officer corps and droid bridge crews, with a Tactical Droid at the tactical station of every major hull. Doctrine prizes patience, concentration of force and preserving hulls over pride.",
  heritage:"Trench's naval school, Techno Union and Commerce Guild fleet auxiliaries, and Quarren shipwright families.",
  mission:"Defend Confederate space, project force when ordered and keep the fleet in being.",
  org:"Fleet, battle group, squadron, ship. Every capital ship has bridge, gunnery, flight, engineering and boarding departments.",
  chain:"Captain, Battle Group Commander, Fleet Admiral (through the Naval Staff), Military Senate, Supreme Commander.",
  reports:"The Naval Staff, then the Military Senate and the Office of the Supreme Commander.",
  assets:"Continuance-class battlecruisers, Providence-pattern carrier-destroyers, Recusant-pattern light destroyers, Munificent-pattern frigates, Lucrehulk-derived droid carriers and tenders.",
  formations:["FO|Navy: held by the Fleet Admiral, who runs the Naval Staff","FO|Fleet (the 9th Fleet, Home Fleet): an Admiral or Vice Admiral with three to five battle groups","FO|Battle group: a Rear Admiral or Commodore with a flagship, a carrier and 8 to 16 escorts","SO|Capital ship: a Captain, with a Commander as executive officer and Lieutenant Commanders as department heads","SO|Escort squadron: a Commander leading four to six frigates or destroyers","JO|Watch section on bridge, gunnery or engineering deck, led by a Lieutenant","MID|Midshipmen rotate through every department of one capital ship","WO|Technical authority over weapons, drives, sensors or flight systems","NCO|Ship's division: Petty and Chief Petty Officers","E|Spacer crew who stand watches in a ship's division"],
  ranks:"Fleet Admiral;Admiral;Vice Admiral;Rear Admiral;Commodore;Captain;Commander;Lieutenant Commander;Senior Lieutenant;Lieutenant;Sub-Lieutenant;Ensign;Midshipman;Master Warrant Officer;Chief Warrant Officer;Warrant Officer;Junior Warrant Officer;Fleet Master Chief;Command Master Chief;Master Chief Petty Officer;Senior Chief Petty Officer;Chief Petty Officer;Petty Officer, First Class;Petty Officer, Second Class;Petty Officer, Third Class;Senior Spacer;Spacer;Spacer Recruit",
  duties:["Command, crew and maintain capital ships and escorts","Plan fleet movements, gunnery and navigation doctrine","Keep every hull ready for sudden fleet action"],
  posts:{ FO:"Commands a fleet, battle group or the Naval Staff.", SO:"Captains a capital ship, leads an escort squadron or heads a ship department.", JO:"Stands bridge, gunnery or engineering watches and commands a watch section.", MID:"Rotates through departments aboard one capital ship while qualifying.", WO:"Technical authority over weapons, drives or sensors.", NCO:"Leads a ship's division or a watch section.", E:"Serves in a working division aboard ship." } },

fighter: { tab:'fleet', label:'Starfighter', name:'Droid Starfighter Corps', fam:'fleet',
  intro:"The Droid Starfighter Corps flies vulture-pattern droid fighters, tri-fighters, hyena-pattern bombers and gunships from carrier decks. Most fighters are droid-brained or piloted by droid units; organic pilots fly command craft and special strikes. Squadrons are mixed flights: organic leaders give improvisation, droid wingmen give endurance and precision.",
  heritage:"Trade Federation droid fighter wings and Colicoid and Geonosian craft design lines.",
  mission:"Win local superiority around the fleet, strike enemy ships and cover boarding actions.",
  org:"Air groups attached to carriers, then squadrons, then flights of four to six craft. Deck crews are attached to each group.",
  chain:"Flight leader, Squadron Commander, Carrier Air Group, Carrier Air Command, Naval Staff.",
  reports:"The Naval Staff through the Carrier Air Command.",
  assets:"Vulture droids, tri-fighters, hyena bombers, Geonosian-pattern interceptors, Sheathipede-pattern shuttles.",
  formations:["FO|Carrier Air Command: an Air Marshal with a staff on the Naval Staff","FO|Air division: an Air Commodore over the groups of one fleet","SO|Carrier Air Group: a Wing Commander over four to six squadrons","SO|Squadron: a Squadron Commander with 36 fighters in six flights","JO|Flight: four to six craft, led by a Flight Captain or Flight Lieutenant","MID|Flight Cadets fly as wingmen under supervision","WO|Flight-systems warrants certify droid brains and fighter avionics","NCO|Deck crews: Flight Chiefs and Deck Technicians","E|Deck hands for rearming, fuelling and launch"],
  ranks:"-;-;-;Air Marshal;Air Commodore;Wing Commander;Wing Executive Officer;Squadron Commander;Squadron Leader;Flight Captain;Flight Lieutenant;Pilot Officer;Flight Cadet;-;Master Flight-Systems Warrant;Chief Flight-Systems Warrant;Flight-Systems Warrant;-;-;Deck Sergeant Major;Master Flight Sergeant;Flight Chief;Flight Sergeant;Senior Deck Technician;Deck Technician;Senior Deck Hand;Deck Hand;Deck Recruit",
  duties:["Fly interception, escort and strike sorties","Coordinate droid wingmen and swarm tactics","Train and certify replacement pilots and droid brains"],
  posts:{ FO:"Commands the air arm of a carrier fleet.", SO:"Leads an air group or squadron.", JO:"Flies and leads a flight in combat.", MID:"Flies as a supervised wingman.", WO:"Certifies droid fighter brains and avionics.", NCO:"Supervises flight deck crews and turnaround.", E:"Rearms, fuels and launches fighters." } },

boarding: { tab:'fleet', label:'Boarding', name:'Boarding & Assault Corps', fam:'ground',
  intro:"The Confederacy never fielded Marines. The Separatist forces were corporate fleets, droid armies and security forces, and the closest tradition was droid boarding: super battle droids, droidekas and commando droids carried in assault shuttles and landing craft to seize a ship from inside. The Boarding & Assault Corps keeps that tradition: it is a droid-heavy ship-seizure and landing arm with a small organic cadre. It replaces any Marine-style service.",
  heritage:"Separatist droid boarding actions, Trade Federation security forces and Techno Union assault droid lines.",
  mission:"Defend ships against boarders, seize enemy ships and secure landing zones for the Army.",
  org:"Boarding companies are attached to capital ships; assault battalions and brigades land as a unit under the Corps staff.",
  chain:"Boarding squad, assault company, assault battalion, Corps staff, Naval Staff, with an Army liaison.",
  reports:"The Corps Staff under the Naval Staff, with an Army liaison.",
  assets:"Boarding shuttles, Droid Gunships, B2 super battle droids, droidekas, BX-pattern commando droids.",
  formations:["FO|Corps: a Corps Marshal on the Naval Staff","FO|Assault brigade: a Brigadier General with three battalions","SO|Assault battalion: a Colonel, droid companies plus an organic cadre","SO|Ship's boarding detachment: a Major or Lieutenant Colonel","JO|Boarding company: a Captain with four platoons","JO|Boarding platoon or assault team: a Lieutenant","MID|Officer Cadets serve as assistant platoon leaders","WO|Breacher warrants for demolitions, breaching and boarding pods","NCO|Squads of ten to twelve units led by a Sergeant","E|Assault troopers, droid and organic"],
  ranks:"-;-;Corps Marshal;Assault General;Brigadier General;Colonel;Lieutenant Colonel;Major;Captain;First Lieutenant;Lieutenant;Second Lieutenant;Officer Cadet;-;Master Breacher Warrant;Chief Breacher Warrant;Breacher Warrant;Command Sergeant Major;Sergeant Major;First Sergeant;Master Sergeant;Staff Sergeant;Sergeant;Corporal;Lance Corporal;Senior Trooper;Trooper;Trooper Recruit",
  duties:["Repel and conduct boarding actions","Guard critical ship compartments and brigs","Seize landing zones for follow-on forces"],
  posts:{ FO:"Commands the Corps or an assault brigade.", SO:"Commands an assault battalion or a capital ship's boarding detachment.", JO:"Leads a company, platoon or boarding team.", MID:"Assistant platoon leader under training.", WO:"Breaching and demolitions specialist.", NCO:"Leads squads and drills the detachment.", E:"Serves in a boarding or assault squad." } },

nint: { tab:'fleet', label:'Navy Intel', name:'Naval Intelligence Directorate', fam:'intel',
  intro:"Naval Intelligence handles signals interception, fleet reconnaissance, counter-espionage and analysis of every vessel the Confederacy has tracked. Officers are embedded aboard warships and at fleet depots and report outside the normal naval chain.",
  heritage:"Trench's reconnaissance staff and Techno Union sensor analysts.",
  mission:"Tell fleet commanders what is out there, and stop anyone telling the wrong people what is in here.",
  org:"Directorate divisions: fleet analysis, signals, counter-espionage, technical collection. Field teams attach to fleet staffs.",
  chain:"Case officer, station chief, division director, Director General, Intelligence Directorate, Supreme Commander.",
  reports:"The Intelligence Directorate, then the Office of the Supreme Commander.",
  assets:"Reconnaissance probes, sensor skiffs, intercept stations, the fleet tracking archive.",
  formations:["FO|Directorate: a Director General","FO|Division (analysis, signals, counter-espionage): a Director","SO|Fleet intelligence station: a Senior Intelligence Officer","JO|Case team or watch desk: a Case Officer","MID|Trainee officers rotate between desks","WO|Technical analysts for signals and sensors","NCO|Collection and analysis desks"],
  ranks:"Director General;Director;Deputy Director;Assistant Director;Chief of Station;Senior Intelligence Officer;Intelligence Officer;Assistant Intelligence Officer;Senior Case Officer;Case Officer;Junior Case Officer;Probationary Case Officer;Trainee Officer;-;Chief Technical Analyst;Technical Analyst;Junior Technical Analyst;-;-;-;Chief Intelligence Specialist;Senior Intelligence Specialist;Intelligence Specialist;Junior Intelligence Specialist;Intelligence Clerk;-;-;-",
  duties:["Intercept, decrypt and analyse signals traffic","Run counter-espionage inside the fleet","Brief fleet commanders on threats and movements"],
  posts:{ FO:"Heads a directorate division or the whole service.", SO:"Runs a fleet intelligence station or analysis cell.", JO:"Works a field team or watch desk.", MID:"Rotating trainee.", WO:"Technical analyst for signals and sensor data.", NCO:"Supports collection and analysis desks." } },

army: { tab:'ground', label:'Army', name:'Confederate Droid Army', fam:'ground',
  intro:"The Confederate Droid Army descends from the Separatist Droid Army: mass battle-droid legions, armour and artillery under Tactical Droids, with an organic officer and NCO cadre that supplies judgement and civil accountability. Droid units provide mass; organic personnel provide discretion, and every formation keeps both on its rolls.",
  heritage:"Trade Federation, Techno Union, Commerce Guild and Corporate Alliance ground forces, merged under the Supreme Commander of the Droid Armies.",
  mission:"Hold Confederate ground, defeat landings and retake lost positions.",
  org:"Army group, corps, division, regiment, battalion, company, platoon, squad. Armour and artillery regiments are attached to divisions.",
  chain:"Platoon, company, battalion, regiment, division, corps, army group, Army General Staff, Military Senate, Supreme Commander.",
  reports:"The Army General Staff, then the Military Senate and the Supreme Commander.",
  assets:"B1 and B2 battle droids, droidekas, AAT and Hailfire armour, artillery tracks, Persuader and Armored Assault Tank lines, Sabaoth-pattern walkers.",
  formations:["FO|Army: the Marshal on the General Staff","FO|Army group (about 300,000 units): a General","FO|Corps (about 90,000): a Lieutenant General","FO|Division (about 12,000): a Major General or Brigadier General","SO|Regiment (about 2,000): a Colonel","SO|Battalion (about 500): a Lieutenant Colonel or Major","JO|Company (about 100): a Captain","JO|Platoon (about 30): a Lieutenant","MID|Officer Cadets serve as assistant platoon leaders","WO|Warrants for maintenance, fire control and signals","NCO|Squads of 8 to 12: Sergeants, with senior NCOs at company and battalion","E|Rifle squad and vehicle crew members"],
  ranks:"Marshal;General;Lieutenant General;Major General;Brigadier General;Colonel;Lieutenant Colonel;Major;Captain;First Lieutenant;Lieutenant;Second Lieutenant;Officer Cadet;Master Warrant Officer;Chief Warrant Officer;Warrant Officer;Junior Warrant Officer;Sergeant Major of the Army;Command Sergeant Major;First Sergeant;Master Sergeant;Staff Sergeant;Sergeant;Corporal;Lance Corporal;Private First Class;Private;Recruit",
  duties:["Garrison, defend and retake fortified positions","Direct armour, artillery and droid infantry","Maintain unit discipline and readiness"],
  posts:{ FO:"Commands an army group, corps or division, or sits on the General Staff.", SO:"Commands a regiment or battalion, or runs a staff section.", JO:"Commands a company or platoon.", MID:"Assistant platoon leader under training.", WO:"Technical authority for maintenance, signals or fire control.", NCO:"Runs squads, platoons and company administration.", E:"Serves in a rifle squad or crew." } },

commando: { tab:'ground', label:'Commando', name:'Commando Corps', fam:'ground',
  intro:"The Commando Corps is the Confederacy's elite strike arm: BX-pattern commando droids and hand-picked organic special forces. Commandos operate in small teams on missions the line army would not survive. Protective duties belong to the Charter Guard, not the Corps.",
  heritage:"Techno Union BX-series commando droids, Geonosian special infiltrators and Hemes Arbora scouts.",
  mission:"Raid, assassinate, recover and infiltrate, on orders from the highest levels only.",
  org:"Brigades divide into strike groups and then teams of four to eight. Teams are mixed organic and droid.",
  chain:"Team, strike group, brigade, Commando Command, Military Senate.",
  reports:"The Commando Command, then directly to the Military Senate.",
  assets:"BX commando droids, stealth insertion craft, long-range infiltration kits, heavy sniper platforms.",
  formations:["FO|Corps: a Corps Commandant","FO|Brigade: a Commando General or Brigadier","SO|Strike group: a Commando Colonel","SO|Battalion: a Commando Major","JO|Company: a Commando Captain","JO|Team (4 to 8): a Commando Lieutenant","MID|Commando Cadets complete the selection course","WO|Weapons, demolitions or infiltration warrants","NCO|Team sergeants and trainers","E|Team operators"],
  ranks:"-;Corps Commandant;Commando General;Commando Brigadier;-;Commando Colonel;Commando Lieutenant Colonel;Commando Major;Commando Captain;Commando First Lieutenant;Commando Lieutenant;Commando Second Lieutenant;Commando Cadet;-;Master Weapons Warrant;Chief Weapons Warrant;Weapons Warrant;-;Corps Sergeant Major;Command Sergeant Major;First Sergeant;Master Sergeant;Team Sergeant;Sergeant;Corporal;Veteran Commando;Commando;Commando Recruit",
  duties:["Conduct raids, assassinations and recovery missions","Infiltrate and sabotage enemy positions","Train and certify special-operations teams"],
  posts:{ FO:"Commands the Corps or a commando brigade.", SO:"Commands a strike group or battalion.", JO:"Leads a commando company or team.", MID:"Candidate in the selection course.", WO:"Weapons, demolitions or infiltration specialist.", NCO:"Team sergeant and trainer.", E:"Serves as a team operator." } },

pdc: { tab:'ground', label:'Planetary Defense', name:'Planetary Defense Command', fam:'ground',
  intro:"Planetary Defense Command runs the fixed defences of the homeworld: shield generators, orbital batteries, sensor-masking arrays and fortress garrisons. It is the reason a hostile fleet would find a quiet world and then a very short battle.",
  heritage:"Separatist fortress-world garrisons and Techno Union defence engineering.",
  mission:"Deny orbit and surface to any hostile force and keep the defences hidden until used.",
  org:"Defence sectors divide into fortresses, batteries and watch stations, each with a fire-control section.",
  chain:"Gun crew, battery, fortress, defence sector, Command staff, Army General Staff and Naval Staff jointly, Military Senate.",
  reports:"The Army General Staff and the Naval Staff jointly, then the Military Senate.",
  assets:"Planetary shield generators, ion and turbolaser batteries, sensor-masking arrays, sealed-door fortress garrisons.",
  formations:["FO|Command: a Defense Marshal","FO|Defence sector: a Defense General or Brigadier","SO|Fortress: a Fortress Commandant","SO|Battery group: a Battery Colonel or Major","JO|Battery: a Battery Captain","JO|Watch section: a Watch Lieutenant","MID|Defense Cadets train at the Fire-Control school","WO|Fire-control and shield-systems warrants","NCO|Gun crews and watch sections","E|Crew and sensor watch"],
  ranks:"-;-;Defense Marshal;Defense General;Defense Brigadier;Fortress Commandant;Battery Colonel;Battery Major;Battery Captain;Battery Lieutenant;Watch Lieutenant;Second Watch Lieutenant;Defense Cadet;-;Chief Fire-Control Warrant;Fire-Control Warrant;Junior Fire-Control Warrant;-;Defense Sergeant Major;Master Gunnery Sergeant;Gunnery Sergeant;Staff Gunner;Sergeant Gunner;Corporal Gunner;Lance Gunner;Senior Gunner;Gunner;Gunner Recruit",
  duties:["Operate shield and orbital battery systems","Maintain sensor-masking and concealment arrays","Drill fortress garrisons for sealed-door defence"],
  posts:{ FO:"Commands a defence sector or the Command staff.", SO:"Commands a fortress or battery group.", JO:"Commands a battery or a watch.", MID:"Fire-control trainee.", WO:"Fire-control and shield-systems technician.", NCO:"Leads gun crews and watch sections.", E:"Serves on a gun crew or sensor watch." } },

aint: { tab:'ground', label:'Army Intel', name:'Army Intelligence Directorate', fam:'intel',
  intro:"Army Intelligence is the ground-side counterpart of Naval Intelligence: battlefield reconnaissance, interrogation, loyalty monitoring of organic units and the dismantling of insurgent cells. Officers are attached to army formations but answer to the Directorate.",
  heritage:"Separatist Army intelligence staff and corporate security-forces analysts.",
  mission:"Give the Army an accurate picture of the ground and of its own reliability.",
  org:"Theatre intelligence stations cover collection, interrogation, security vetting and mapping.",
  chain:"Field officer, theatre chief, division director, Director General, Intelligence Directorate, Supreme Commander.",
  reports:"The Intelligence Directorate, then the Office of the Supreme Commander.",
  assets:"Reconnaissance droids, interrogation facilities, battlefield mapping archives.",
  formations:["FO|Directorate: a Director General","FO|Theatre station: a Theatre Chief","SO|Corps-level intelligence staff: a Senior Intelligence Officer","JO|Field cell: a Field Officer","MID|Trainee officers","WO|Field analysts","NCO|Interrogation and vetting desks"],
  ranks:"Director General;Director;Deputy Director;Assistant Director;Theatre Chief;Senior Intelligence Officer;Intelligence Officer;Assistant Intelligence Officer;Senior Field Officer;Field Officer;Junior Field Officer;Probationary Field Officer;Trainee Officer;-;Chief Field Analyst;Field Analyst;Junior Field Analyst;-;-;-;Chief Interrogator;Senior Interrogator;Interrogator;Junior Interrogator;Intelligence Clerk;-;-;-",
  duties:["Gather and assess battlefield intelligence","Interrogate prisoners and defectors","Audit unit loyalty and security"],
  posts:{ FO:"Heads a directorate division.", SO:"Runs a theatre intelligence station.", JO:"Leads a field cell.", MID:"Rotating trainee.", WO:"Specialist field analyst.", NCO:"Conducts interrogations and vetting." } },

eng: { tab:'support', label:'Engineering', name:'Engineering Corps', fam:'support',
  intro:"The Engineering Corps builds, repairs and conceals. It carries the Techno Union's engineering tradition and the Geonosian hive-builders' skills: it excavates the underground cities, maintains the shield and power grid, and keeps every hull seaworthy.",
  heritage:"Techno Union engineering divisions and Geonosian hive engineers.",
  mission:"Build and maintain the physical state: cities, power, shipyards and defences.",
  org:"Divisions: civil construction, ship repair, power systems, concealment works.",
  chain:"Crew chief, section engineer, division director, Director-General, Directorate of Auxiliary Services.",
  reports:"The Directorate of Auxiliary Services, then the Military Senate.",
  assets:"Excavator droids, shipyard cranes, power plants, sensor-masking works.",
  formations:["FO|Corps: the Director-General","FO|Works division: a Director of Works","SO|Major project or yard: a Chief Engineer","JO|Section: an Engineer","MID|Technical Cadets","WO|Master of a trade or system","NCO|Work crews","E|Mechanics and builders"],
  ranks:"-;Director-General of Engineers;Deputy Director-General;Director of Works;Deputy Director of Works;Chief Engineer;Senior Engineer;Engineer;Associate Engineer;Senior Technician Officer;Technician Officer;Junior Technician Officer;Technical Cadet;Grand Master Technician;Master Technician;Chief Technician;Technician;-;Master Craftsman;-;Chief Foreman;Senior Foreman;Foreman;Senior Crew Chief;Crew Chief;Senior Mechanic;Mechanic;Mechanic Apprentice",
  duties:["Excavate, construct and repair installations","Maintain the power grid and shield generators","Repair and refit ships and droids"],
  posts:{ FO:"Directs a works division or the whole Corps.", SO:"Chief engineer of a major project or yard.", JO:"Leads an engineering section.", MID:"Technical cadet.", WO:"Master of a trade or system.", NCO:"Foreman of a work crew.", E:"Works as a mechanic or builder." } },

log: { tab:'support', label:'Logistics', name:'Logistics & Foundry Command', fam:'support',
  intro:"Logistics and Foundry Command is the military side of the Ministry of Resource Continuance. It carries the Commerce Guild's freight and transport tradition and the Techno Union's foundry tradition: mines, automated foundries, depots and the convoys between them.",
  heritage:"Commerce Guild transport and Techno Union foundries.",
  mission:"Keep every unit supplied and the foundries producing.",
  org:"Divisions: supply, transport, foundry operations and strategic reserves.",
  chain:"Handler, supply sergeant, depot commander, Quartermaster General, Directorate of Auxiliary Services.",
  reports:"The Directorate of Auxiliary Services, with oversight by the Ministry of Resource Continuance.",
  assets:"Droid foundries, cargo haulers, strategic reserve vaults, convoy escorts.",
  formations:["FO|Command: the Quartermaster General","FO|Division (supply or foundry): a Director","SO|Depot, foundry complex or convoy group: a Chief Quartermaster","JO|Supply section: a Supply Officer","MID|Supply Cadets","WO|Foundry and inventory warrants","NCO|Loader and convoy crews","E|Stores and loading hands"],
  ranks:"-;Quartermaster General;Deputy Quartermaster General;Director of Supply;Director of Foundries;Chief Quartermaster;Senior Quartermaster;Quartermaster;Assistant Quartermaster;Senior Supply Officer;Supply Officer;Junior Supply Officer;Supply Cadet;Grand Master Foundry Warrant;Master Foundry Warrant;Chief Foundry Warrant;Foundry Warrant;-;Master Supply Sergeant;-;Chief Supply Sergeant;Senior Supply Sergeant;Supply Sergeant;Senior Loader;Loader Chief;Senior Handler;Supply Handler;Supply Apprentice",
  duties:["Move and store ammunition, fuel and spares","Operate and schedule automated foundries","Audit strategic reserves and consumption"],
  posts:{ FO:"Directs a supply or foundry division.", SO:"Commands a depot, foundry complex or convoy group.", JO:"Runs a supply section.", MID:"Supply cadet.", WO:"Foundry or inventory specialist.", NCO:"Supervises loaders and convoy crews.", E:"Works in stores, loading and transport." } },

med: { tab:'support', label:'Medical', name:'Medical Corps', fam:'support',
  intro:"The Medical Corps cares for organic personnel and also maintains the droid repair wards. It runs field hospitals, ship sick bays and the public health service of the civilian districts.",
  heritage:"Corporate medical services and Hemes Arbora healers.",
  mission:"Keep personnel fit for service and the civilian population healthy.",
  org:"Medical commands serve the fleet, army and civil districts, each with hospitals, clinics and aid stations.",
  chain:"Medic, chief medic, hospital chief, Surgeon General, Directorate of Auxiliary Services.",
  reports:"The Directorate of Auxiliary Services, with the Ministry of Health for civil matters.",
  assets:"Field hospitals, ship sick bays, droid repair wards.",
  formations:["FO|Corps: the Surgeon General","FO|Medical command (fleet, army or civil): a Medical Director","SO|Hospital or fleet medical staff: a Chief Surgeon","JO|Ward or ship's sick bay: a Physician","MID|Medical Cadets","WO|Laboratory and surgical technicians","NCO|Aid stations and medic teams","E|Nursing and first aid"],
  ranks:"-;Surgeon General;Deputy Surgeon General;Medical Director;Deputy Medical Director;Chief Surgeon;Senior Surgeon;Surgeon;Medical Officer;Senior Physician;Physician;Junior Physician;Medical Cadet;-;Master Medical Technician;Chief Medical Technician;Medical Technician;-;Master Medic Sergeant;-;Chief Medic;Senior Medic;Staff Medic;Medic;Junior Medic;Senior Orderly;Orderly;Medical Recruit",
  duties:["Treat casualties and run field hospitals","Maintain ship sick bays and droid repair wards","Administer public health and quarantine"],
  posts:{ FO:"Directs a medical command or the Corps.", SO:"Chief of a hospital or fleet medical staff.", JO:"Staff physician or surgeon.", MID:"Medical cadet.", WO:"Laboratory and surgical technician.", NCO:"Leads medic teams and aid stations.", E:"Provides nursing and first aid." } },

rnd: { tab:'support', label:'R&D', name:'Research & Development Bureau', fam:'support',
  intro:"The Research and Development Bureau designs the next generation of Confederate hardware: warships, droid cores, weapons and sensor-masking technology. Its laboratories sit behind the deepest security in the state.",
  heritage:"Techno Union research divisions and Geonosian weapon designers.",
  mission:"Keep the Confederacy technically ahead of anyone who might find it.",
  org:"Research divisions: naval design, droid cores, weapons, materials and concealment technology.",
  chain:"Test technician, laboratory head, programme director, Chief Scientist, Supreme Commander on core matters.",
  reports:"The Directorate of Auxiliary Services, with direct access to the Supreme Commander on core matters.",
  assets:"Test ranges, droid core laboratories, materials plants.",
  formations:["FO|Bureau: the Chief Scientist","FO|Research programme: a Director of Research","SO|Laboratory or project: a Principal Scientist","JO|Research team: a Research Officer","MID|Research Cadets","WO|Laboratory and test specialists","NCO|Test ranges and workshops"],
  ranks:"-;Chief Scientist;Deputy Chief Scientist;Director of Research;Deputy Director of Research;Principal Scientist;Senior Scientist;Scientist;Associate Scientist;Senior Research Officer;Research Officer;Junior Research Officer;Research Cadet;-;Master Laboratory Technician;Chief Laboratory Technician;Laboratory Technician;-;-;-;Chief Test Technician;Senior Test Technician;Test Technician;Junior Test Technician;-;-;-;-",
  duties:["Develop and test new ships, weapons and droid cores","Evaluate captured and foreign technology","Protect research from leakage"],
  posts:{ FO:"Directs a research programme or the Bureau.", SO:"Leads a laboratory or project.", JO:"Works on a research team.", MID:"Research cadet.", WO:"Test and laboratory specialist.", NCO:"Runs test ranges and workshops." } },

sig: { tab:'support', label:'Signals', name:'Signals & Communications Service', fam:'support',
  intro:"The Signals and Communications Service runs the Confederacy's secure networks, the deep-space relays and the tightly controlled outbound links used by the Veil Network. It also enforces transmission discipline across the fleet.",
  heritage:"Hyper Communications Cartel (Po Nudo's holdings).",
  mission:"Move information securely and keep the Confederacy's signature close to zero.",
  org:"Divisions: internal networks, fleet communications, relay stations and signal security.",
  chain:"Operator, relay chief, signals officer, Director of Signals, Directorate of Auxiliary Services.",
  reports:"The Directorate of Auxiliary Services, with signal security reporting to Intelligence.",
  assets:"Hypercomm relays, tight-beam networks, emission-control systems.",
  formations:["FO|Service: the Director of Signals","FO|Network division: a Chief Signals Officer","SO|Fleet or station communications: a Senior Signals Officer","JO|Watch: a Network Officer","MID|Signals Cadets","WO|Encryption and systems specialists","NCO|Operators and relay crews"],
  ranks:"-;Director of Signals;Deputy Director of Signals;Chief Signals Officer;Deputy Chief Signals Officer;Senior Signals Officer;Signals Officer;Communications Officer;Associate Signals Officer;Senior Network Officer;Network Officer;Junior Network Officer;Signals Cadet;-;Master Signals Warrant;Chief Signals Warrant;Signals Warrant;-;Master Signals Sergeant;-;Chief Signaller;Senior Signaller;Signaller;Senior Operator;Operator;Junior Operator;Operator Trainee;Operator Recruit",
  duties:["Operate secure networks and relays","Enforce emission control across the fleet","Maintain encryption and key management"],
  posts:{ FO:"Directs communications for a command or the Service.", SO:"Chief signals officer of a fleet or station.", JO:"Runs a communications watch.", MID:"Signals cadet.", WO:"Systems and encryption specialist.", NCO:"Supervises operators and relay crews.", E:"Operates consoles and relays." } },

droid: { tab:'droid', label:'Droid Command', name:'Droid Command Corps', fam:'droid',
  intro:"Five centuries of self-replicating foundries produced a droid officer class that descends from the Separatist command droids (OOM-series, tactical droids and Super Tactical Droids). Droid ranks are functional designations rather than rewards and each unit carries its serial designation with its rank. The Supreme Commander, Vexis, is the corps' apex.",
  heritage:"Techno Union super tactical droid line, Trade Federation OOM command droids and Trench's neural pattern.",
  mission:"Provide reliable, tireless command and line capability across every branch.",
  org:"Droid commands are attached to branches but certified by the Corps. Each droid unit is paired with an organic liaison by charter.",
  chain:"Line droid, squad leader, command droid, tactical droid, Droid Command Staff, Supreme Commander.",
  reports:"The Droid Command Staff, then directly to the Supreme Commander.",
  assets:"Super Tactical Droids, Tactical Droids, OOM command droids, B1 and B2 line units.",
  formations:["FO|Droid Command Staff: the Super Tactical Droid","FO|Theatre or fleet droid command: a Tactical Droid","SO|Droid battalion or capital ship droid complement: a Command Droid","JO|Droid company or platoon: a Captain or Lieutenant Droid","MID|Probationary units under software audit","WO|Specialised systems droids with locked skill cores","NCO|Droid squads: Sergeant Droids","E|Line units by serial designation"],
  ranks:"Super Tactical Droid;Tactical Droid Prime;Tactical Droid;Strategic Command Droid;Senior Command Droid;Command Droid Prime;Command Droid;Lieutenant Command Droid;Captain Droid;Lieutenant Droid;Second Lieutenant Droid;Junior Lieutenant Droid;Probationary Droid;Master Systems Droid;Chief Systems Droid;Systems Droid;Technical Droid;-;Sergeant Major Droid;-;Master Sergeant Droid;Staff Sergeant Droid;Sergeant Droid;Squad Leader Droid;Corporal Droid;Elite Line Droid;Line Droid;Newly Activated Droid",
  duties:["Command droid formations in every branch","Operate under certified learning-core limits","Pair with organic liaison officers for oversight"],
  posts:{ FO:"Strategic and theatre-level droid command.", SO:"Commands droid battalions and ships' droid complements.", JO:"Leads droid companies and platoons.", MID:"Probationary unit under software audit.", WO:"Specialised systems droid with locked skill cores.", NCO:"Runs droid squads and discipline.", E:"Line unit assigned by serial." } },

liaison: { tab:'droid', label:'Droid Liaison', name:'Droid Liaison Service', fam:'droid',
  intro:"The Droid Liaison Service supplies the organic officers who oversee droid commands as required by the Provincial Charter. Liaison officers hold a veto on droid orders that touch civilian life or constitutional matters.",
  heritage:"A post-war creation of the Charter; the Separatists never needed one.",
  mission:"Ensure droid command remains accountable to organic oversight and to the Charter.",
  org:"Liaison officers attach to droid commands at ship, regiment and staff levels.",
  chain:"Liaison officer, senior liaison, Chief of Liaison, Droid Oversight Committee, Military Senate.",
  reports:"The Military Senate's Droid Oversight Committee.",
  assets:"Order-review terminals and audit logs.",
  formations:["FO|Service: the Chief of Liaison","FO|Division: a Senior Liaison General","SO|Regiment, ship or staff: a Liaison Colonel","JO|Company or watch: a Liaison Captain or Lieutenant","MID|Liaison Cadets","NCO|Liaison for droid squads"],
  ranks:"-;-;Chief of Liaison;Deputy Chief of Liaison;Senior Liaison General;Liaison Colonel;Liaison Lieutenant Colonel;Liaison Major;Liaison Captain;Liaison Lieutenant;Second Liaison Lieutenant;Junior Liaison Lieutenant;Liaison Cadet;-;-;-;-;-;-;-;Senior Liaison Sergeant;Liaison Sergeant;Liaison Corporal;-;-;-;-;-",
  duties:["Review droid orders for Charter compliance","Advise droid commanders on organic morale and law","Report irregularities to the Droid Oversight Committee"],
  posts:{ FO:"Heads the Service or a major liaison division.", SO:"Senior liaison at a regiment, ship or staff.", JO:"Liaison to a droid company or watch.", MID:"Liaison cadet.", NCO:"Non-commissioned liaison for droid squads." } },

psb: { tab:'intel', label:'Security Bureau', name:'Provincial Security Bureau', fam:'intel',
  intro:"The Provincial Security Bureau is the domestic intelligence and internal security agency. It investigates sedition, sabotage and espionage, protects the Provincial Charter and polices the civilian districts alongside the Constabulary.",
  heritage:"Separatist Council security services and corporate security forces.",
  mission:"Protect the Charter, the state and its secrets from internal threats.",
  org:"Divisions: counter-espionage, sedition, vetting, district offices and technical surveillance.",
  chain:"Agent, special agent in charge, division director, Director General, Military Senate, Supreme Commander.",
  reports:"The Military Senate and, constitutionally, the Supreme Commander.",
  assets:"Surveillance networks, forensic laboratories, detention facilities.",
  formations:["FO|Bureau: a Director General","FO|Division: a Director","SO|District office or investigative division: a Chief Special Agent","JO|Case team: an Agent First Class","MID|Trainee agents","WO|Forensic and technical examiners","NCO|Enforcement and surveillance support"],
  ranks:"Director General;Director;Deputy Director;Assistant Director;District Chief;Chief Special Agent;Senior Special Agent;Special Agent;Agent First Class;Agent;Junior Agent;Probationary Agent;Trainee Agent;-;Chief Examiner;Examiner;Junior Examiner;-;-;-;Chief Enforcement Officer;Senior Enforcement Officer;Enforcement Officer;Junior Enforcement Officer;Surveillance Operative;-;-;Bureau Recruit",
  duties:["Investigate sedition, sabotage and foreign espionage","Protect constitutional offices and installations","Conduct personnel vetting and security audits"],
  posts:{ FO:"Directs a Bureau division or the Bureau.", SO:"Heads a district office or investigative division.", JO:"Leads a case team.", MID:"Trainee agent.", WO:"Forensic and technical examiner.", NCO:"Enforcement and surveillance support.", E:"Surveillance and support staff." } },

veil: { tab:'intel', label:'Veil Network', name:'The Veil Network', fam:'veil',
  intro:"The Veil Network is the Confederacy's clandestine foreign intelligence service, founded by the Veiled Accord and formalised under Vexis. Operatives live ordinary lives in distant societies, pass fragments through cut-outs and dead drops and are never told where those fragments end up. Ranks are known only inside the Network.",
  heritage:"The Veiled Accord's covert web and the corporate informant networks.",
  mission:"Watch the wider galaxy without ever being seen doing it.",
  org:"Regional stations manage handlers, who manage operatives, who manage contacts. No operative knows more than two levels above or below.",
  chain:"Contact, courier, operative, handler, station, region, Veilmaster, Supreme Commander.",
  reports:"Directly to the Office of the Supreme Commander.",
  assets:"Cover identities, cut-out chains, dead drops, courier ships.",
  formations:["FO|Network: the Veilmaster","FO|Region and sector: Regional and Sector Directors","SO|Station: a Station Chief","JO|Operative cell: a Handler","MID|Initiates trained for a long placement","WO|Cryptographers","NCO|Couriers and cut-outs","E|Local informants"],
  ranks:"Veilmaster;Deputy Veilmaster;Regional Director;Sector Director;Station Director;Station Chief;Senior Handler;Handler;Assistant Handler;Senior Operative;Operative;Field Agent;Initiate;-;Master Cryptographer;Cryptographer;Cipher Clerk;-;-;-;Chief Courier;Senior Courier;Courier;Cut-Out;Dead-Drop Keeper;Informant;Contact (Asset);-",
  duties:["Run agents and cut-outs in foreign societies","Collect and route intelligence through secure channels","Maintain cover identities and withdraw assets safely"],
  posts:{ FO:"Directs a vast region or the whole Network.", SO:"Runs a regional station.", JO:"Handles operatives in a sector.", MID:"Trained for a long-term placement.", WO:"Handles ciphers and secure transmission.", NCO:"Moves material and messages between cells.", E:"Provides local information." } },

cry: { tab:'intel', label:'Cryptology', name:'Cryptology & Counter-Signals Bureau', fam:'intel',
  intro:"The Cryptology and Counter-Signals Bureau breaks other people's codes and keeps the Confederacy's own unbreakable. It holds the largest archive of intercepted galactic traffic anywhere.",
  heritage:"Hyper Communications Cartel analysts and Techno Union cipher engineers.",
  mission:"Decode what is intercepted and secure what is sent.",
  org:"Divisions: cryptanalysis, key production, intercept stations and traffic analysis.",
  chain:"Operator, section chief, division chief, Director of Cryptology, Intelligence Directorate.",
  reports:"The Intelligence Directorate.",
  assets:"Intercept stations, key vaults, the traffic archive.",
  formations:["FO|Bureau: the Director of Cryptology","FO|Division: a Chief Cryptanalyst","SO|Section: a Principal Cryptanalyst","JO|Analysis team: an Analyst","MID|Analyst Cadets","WO|Key-production and cipher specialists","NCO|Intercept station crews"],
  ranks:"-;Director of Cryptology;Deputy Director of Cryptology;Chief Cryptanalyst;Deputy Chief Cryptanalyst;Principal Cryptanalyst;Senior Cryptanalyst;Cryptanalyst;Associate Cryptanalyst;Senior Analyst;Analyst;Junior Analyst;Analyst Cadet;-;Master Key Warrant;Chief Key Warrant;Key Warrant;-;-;-;Chief Intercept Operator;Senior Intercept Operator;Intercept Operator;Junior Intercept Operator;Intercept Trainee;-;-;-",
  duties:["Break foreign ciphers and traffic","Produce and distribute Confederate keys","Audit transmission discipline"],
  posts:{ FO:"Directs the Bureau or a major division.", SO:"Heads a cryptanalysis section.", JO:"Works on an analysis team.", MID:"Analyst cadet.", WO:"Key-production and cipher specialist.", NCO:"Operates intercept stations." } },

guard: { tab:'intel', label:'Charter Guard', name:'Charter Guard', fam:'police',
  intro:"The Charter Guard protects the offices and persons named in the Provincial Charter: the Supreme Commander's office, the Minister President, the Assembly and the Constitutional Court. It is a mixed service of organic guardsmen and the MagnaGuard Order, a droid bodyguard tradition descended from General Grievous' elite guards. It is distinct from the line army and the Commando Corps.",
  heritage:"MagnaGuard-pattern bodyguards, electrostaff drill and Techno Union ceremonial guard units.",
  mission:"Protect the constitutional offices and the places they work.",
  org:"Guard details attach to each protected office; a central staff manages training, vetting and rapid-response teams.",
  chain:"Guardsman, detail sergeant, detail commander, Commandant, Security Committee, Military Senate.",
  reports:"The Military Senate's Security Committee.",
  assets:"MagnaGuards, electrostaves, secured transport, access-control systems.",
  formations:["FO|Guard: the Commandant","FO|Protective division: a Guard General or Brigadier","SO|Detail for one office: a Guard Colonel","JO|Protective team: a Guard Captain or Lieutenant","MID|Guard Cadets","WO|Protective-systems warrants","NCO|Posts and details","E|Guardsmen on posts"],
  ranks:"-;Commandant of the Guard;Deputy Commandant;Guard General;Guard Brigadier;Guard Colonel;Guard Lieutenant Colonel;Guard Major;Guard Captain;Guard Lieutenant;Second Guard Lieutenant;Junior Guard Lieutenant;Guard Cadet;-;-;Master Protective Warrant;Protective Warrant;-;Guard Sergeant Major;Guard First Sergeant;Guard Master Sergeant;Guard Staff Sergeant;Guard Sergeant;Guard Corporal;Lance Corporal;Senior Guardsman;Guardsman;Guard Recruit",
  duties:["Protect constitutional offices and persons","Control access to protected buildings","Respond to threats against officeholders"],
  posts:{ FO:"Commands the Guard.", SO:"Commands a protective division or detail.", JO:"Leads a protective team.", MID:"Guard cadet.", WO:"Protective-systems specialist.", NCO:"Leads details and posts.", E:"Serves on a post or detail." } },

vigil: { tab:'intel', label:'Brotherhood', name:'Brotherhood of Osseriton', fam:'vigil',
  intro:"The Brotherhood of Osseriton, called the Order of the Vigil within its own walls and \"the Quiet Brothers\" in the Veil's designation, is the Provincial Authority's sealed order of sensitives: a closed brotherhood of no more than one hundred, bound by the Covenant and answerable to the Supreme Commander alone. The Veil Network finds sensitives in the wider galaxy and smuggles them to Osseriton; the Vigil raises, tests and sworn-binds them. Its members are sent out on writs to hunt rogue sensitives, guard secrets, silence loose ends and kill targets. Every Sworn is paired for life with a droid Counsel.",
  heritage:"Founded under Vexis. Its recruits come from the Veil Network's finds and from children born on Osseriton who test strong. Its law is the Covenant; its ceiling is the Measure.",
  mission:"Keep the Confederacy's secrets by hunting, guarding and, when ordered, killing, without ever being seen to do so.",
  org:"Vigil Halls train and induct; field cells of Sworn operate under Priors; the Chapter governs. Two hands serve the Magister: the Marshal (field arm) and the Seneschal (discipline, records and the Vaults). The Measure caps the whole Order at one hundred.",
  chain:"Sworn, Prior, Preceptor, Marshal or Seneschal, Magister, Supreme Commander. The Seneschal stands beside the Marshal, not above or below.",
  reports:"The Magister, who answers to the Supreme Commander alone. The Marshal liaises with the Military Senate.",
  assets:"Droid Counsels, the Vigil Halls, the Counsel-archive, the Vaults, the Ledger of the Fallen, and the writs that send a brother into the field.",
  formations:["FO|The Order: the Magister, with the Marshal and the Seneschal as his two hands","FO|The Chapter: the Magister, Marshal, Seneschal and all Preceptors; it votes on every elevation","SO|Vigil Hall: a Preceptor, with its Oblates, Aspirants and Novices","SO|Field cell: a Prior with two to four Sworn","JO|Sworn on writ: a full operative paired with a droid Counsel; may hold a Calling (Edge, Shroud or Eye)","MID|Novice: bonded to one mentor of Sworn rank or higher","E|Aspirant: an adult candidate on trial, watched in a Hall","E|Oblate: a child ward of the Order, unsworn"],
  ranks:"Magister;Marshal;-;-;-;Preceptor;-;Prior;-;-;Sworn;-;Novice;-;-;-;-;-;-;-;-;-;-;-;-;-;Aspirant;Oblate",
  duties:["Hunt rogue sensitives and silence loose ends","Guard Confederate secrets and the persons who hold them","Train and sworn-bind every new brother under the Covenant","Carry out writs ordered by the Magister"],
  posts:{ FO:"Governs the Order or heads its field arm or its discipline and records.", SO:"Commands a Vigil Hall or leads a field cell.", JO:"Serves on writ as a full operative with a droid Counsel.", MID:"Trains as a shadow to one mentor.", E:"Under trial or in the Order's care; unsworn or newly tested." },
  doctrine:"One hundred is enough. A secret kept by few is kept longer. Act only on a writ; report when the work is done; leave nothing for the galaxy to find.",
  training:"Years inside the Vigil Halls. An Oblate learns by repetition; an Aspirant is tested for temperament, loyalty and aptitude; a Novice spends about a decade bonded to a mentor in sparring, covercraft, the Creed and the Counsel-archive.",
  notable:"The Chapter; the three Callings (Edge, Shroud, Eye); the Vigil Halls (including the Second Hall, where the annual trial-by-combat is held); the Vaults; the Ledger of the Fallen; Champion of the Halls, currently Sworn Kaelen Roth.",
  traditions:"Three Oaths mark the crossings: the Novice, the Sworn and Consecration into a Calling. The Seneschal records each in his own hand and the droid Counsel witnesses. The Seneschal recites the Covenant and keeps the Ledger of the Fallen. Washing out is honourable. An Oblate who leaves at adulthood walks away with no shame and no debt.",
  lateral:{ tier:'FO-4', rank:'Seneschal' },
  noInsignia:"Every rank of the Brotherhood bears the hexagon-and-eye mark.",
  advance:"Every advancement needs three things: time served, an aptitude shown and a sponsor of higher rank who vouches for the candidate to the Chapter. The Chapter (Magister, Marshal, Seneschal and all Preceptors) votes; the Magister ratifies and may veto any name without explanation. The Measure caps the Order at one hundred, so a brother rises when someone above him dies, leaves, or the Order admits fewer than it loses.",
  droidHead:"COUNSEL AND OATHS",
  droidNote:"Every Sworn is paired for life with a droid Counsel. A Counsel witnesses each of the three Oaths, which the Seneschal records in his own hand. Only the Magister may speak to Vexis face to face.",
  level:{ 'FO-5':'Sole head of the Order and keeper of the Covenant. Answers to the Supreme Commander alone and to no one inside the Order.', 'FO-4':'One of the Magister\'s two hands. The Order\'s field arm (Marshal) or its discipline and records (Seneschal). A senior voice in the Chapter.', 'SO-3':'Teaching rank and regional head. Runs a Vigil Hall and sits on the Chapter.', 'SO-1':'First command rank. Leads a field cell of two to four Sworn and answers for their deaths.', 'JO-2':'The working heart of the Order. A full operative on writ with a droid Counsel.', 'MID-1':'Sworn trainee bonded to one mentor. First oath taken.', 'E-2':'Adult candidate on trial. Testing for temperament, loyalty, Force aptitude and tolerance for pain and boredom.', 'E-1':'The lowest rung and the only one not sworn. A child ward of the Order.' },
  special:{
    'Magister':'THE SOLE HEAD OF THE ORDER. Keeper of the Covenant and the only brother permitted to speak to Vexis face to face. Governs absolutely within the Covenant and the state\'s writ, holds veto over the Chapter and may convene or dismiss it at will. Names the Marshal and the Seneschal. ENTRY: chosen by the two hands and confirmed by Vexis; lifetime appointment. EXIT: death. A Magister who becomes unfit is not deposed; he is waited out. NUMBER: 1.',
    'Marshal':'THE ORDER\'S MILITARY HEAD, one of the Magister\'s two hands. Commands all field operations, liaises with the Military Senate and holds the war-plan. Always an Edge-brother. Can task any brother below the Magister and answers for every writ carried out. ENTRY: selected by the Magister, usually from the Edge, confirmed by the Chapter. EXIT: death, or elevation to Magister. NUMBER: 1.',
    'Seneschal':'THE ORDER\'S ADMINISTRATIVE HEAD AND CONSCIENCE, the second hand of the Magister. A lateral post, deliberately not on the command ladder: it stands beside the Marshal so that neither grows too strong. Keeps discipline, oaths, records, assignments and internal law; keeps the Ledger of the Fallen; recites the Covenant; adjudicates disputes between Edge and Shroud; runs the Vaults. Can censure even a Marshal, though the Magister is the final court. Often an Eye-brother. ENTRY: elevated by the Magister from a Sworn or Prior of exceptional judgement. EXIT: death or, rarely, the Magister\'s seat. NUMBER: 1.',
    'Preceptor':'A TEACHING RANK AND REGIONAL HEAD. Commands a Vigil Hall (recruitment, training, induction), oversees the Oblates, Aspirants and Novices in it, sits on the Chapter and sets doctrine with the Magister. Rarely leaves his Hall and rarely fights. ENTRY: selected by the Magister from proven Priors. EXIT: elevation to Marshal or Seneschal, or death in the Hall. NUMBER: 2 to 3.',
    'Prior':'THE FIRST COMMAND RANK. Leads a small cell of two to four Sworn, plans and runs field operations, assigns his brothers and takes responsibility for their deaths. Reports to a Preceptor or the Marshal. ENTRY: proven field record and the Marshal\'s sponsorship; the Chapter confirms. EXIT: elevation to Preceptor, or service until death. NUMBER: 3 to 5.',
    'Sworn':'A FULL OPERATIVE, the rank that actually does the job. Takes the Oath of the Sworn, is paired for life with a droid Counsel and is sent on writs: hunting rogue sensitives, silencing loose ends, guarding secrets, killing targets. Alone in the field he answers to no one until he reports. May take the Oath of Consecration into a Calling (Edge, Shroud or Eye), which turns a generalist into a specialist. ENTRY: completing the Novice decade and passing the Chapter\'s judgment. EXIT: death, the Ledger, or elevation. NUMBER: 10 to 15.',
    'Novice':'A SWORN TRAINEE, bonded for the duration to one mentor of Sworn rank or higher. Trains in sparring, covercraft, the Creed and the Counsel-archive, and shadows the mentor in the field. Must obey the mentor absolutely; holds authority over Oblates only. ENTRY: the Oath of the Novice before the Chapter. EXIT: about a decade of training, then the Oath of the Sworn. NUMBER: 5 to 12.',
    'Aspirant':'AN ADULT CANDIDATE ON TRIAL. Either a grown Oblate who chose to stay or a sensitive the Veil found already grown. Assigned to a Hall and watched constantly; no specialty yet. Trusted with real tasks but holds no authority. ENTRY: by choice after Oblacy, or Veil recruitment as an adult. EXIT: months to years of trial; most wash out. Those who pass take the Oath of the Novice. NUMBER: 3 to 8.',
    'Oblate':'A CHILD GIVEN TO THE ORDER, smuggled in by the Veil or born on Osseriton and tested strong. Not sworn. Learns, serves and watches; carries, cleans and runs errands for Novices and the Sworn, absorbing the Creed by repetition before understanding it. Answers to any sworn brother and holds no authority. ENTRY: given as a child or offered as a ward; no oath. EXIT: at adulthood an Oblate may leave freely, the only clean exit in the Order. Those who stay become Aspirants. NUMBER: 5 to 15.'
  } },

admin: { tab:'gov', label:'Administration', name:'Provincial Administration', fam:'civil',
  intro:"The Provincial Administration is the civil half of the Provincial Charter: the ministries that run agriculture, industry, education, justice and resource management. Civil officials answer to the Civilian Council and, in security matters, to the Supreme Commander's veto.",
  heritage:"CIS provincial statutes and the Hemes Arbora councils.",
  mission:"Run the civil state: districts, ministries and public services.",
  org:"Ministries divide into departments, district offices and local sections.",
  chain:"Clerk, administrator, prefect, Cabinet Minister, Minister President, Civilian Council.",
  reports:"The Minister President, then the Civilian Council.",
  assets:"District offices, registries and the civil archive.",
  formations:["FO|Cabinet: the Minister President","FO|Ministry: a Cabinet Minister","SO|Department or district: a Provincial Governor","JO|Local office: an Administrator","MID|Civil academy cadets","WO|Records and registry specialists","NCO|Supervising clerks","E|Counters and offices"],
  ranks:"-;Minister President;Deputy Minister President;Cabinet Minister;Deputy Minister;Chief Administrator;Provincial Governor;Senior Administrator;District Prefect;Assistant Prefect;Administrator;Assistant Administrator;Civil Cadet;-;Chief Registrar;Registrar;Junior Registrar;-;-;-;Chief Clerk;Senior Clerk;Clerk;Junior Clerk;Civil Servant;-;Civil Servant, Provisional;Civil Trainee",
  duties:["Administer ministries and districts","Allocate resources and manage quotas","Implement legislation passed by the Provincial Assembly"],
  posts:{ FO:"Leads a ministry or the whole administration.", SO:"Directs a department or governs a district.", JO:"Manages a local office.", MID:"Trains in the civil service.", WO:"Records and registry specialist.", NCO:"Supervises clerks.", E:"Staffs counters and offices." } },

treasury: { tab:'gov', label:'Treasury', name:'Treasury & Audit Bureau', fam:'civil',
  intro:"The Treasury and Audit Bureau issues the Confederate Credit, audits every ministry and branch and keeps the books of the Ministry of Resource Continuance. It carries the tradition of the Banking Clan's auditors, repurposed for a closed single-world economy.",
  heritage:"InterGalactic Banking Clan and Commerce Guild accountancy.",
  mission:"Keep the Confederate Credit sound and the ledgers honest.",
  org:"Divisions: currency, audit, reserves and resource accounts.",
  chain:"Ledger clerk, auditor, Chief Auditor, Treasurer General, Minister President.",
  reports:"The Minister President, with an audit line to the Military Senate.",
  assets:"The credit mint, reserve vaults and ledger archives.",
  formations:["FO|Bureau: the Treasurer General","FO|Audit division: a Chief Auditor","SO|Branch audit: a Senior Auditor","JO|Audit team: an Accountant","MID|Audit cadets","WO|Ledger warrants","NCO|Bookkeeping staff"],
  ranks:"-;Treasurer General;Deputy Treasurer General;Chief Auditor;Deputy Chief Auditor;Senior Auditor;Auditor;Assistant Auditor;Accountant First Class;Accountant;Junior Accountant;Probationary Accountant;Audit Cadet;-;Chief Ledger Warrant;Ledger Warrant;Junior Ledger Warrant;-;-;-;Chief Bookkeeper;Senior Bookkeeper;Bookkeeper;Junior Bookkeeper;Ledger Clerk;-;-;Clerk Trainee",
  duties:["Issue and secure the Confederate Credit","Audit ministries and military branches","Manage strategic reserve accounting"],
  posts:{ FO:"Directs the Bureau or an audit division.", SO:"Heads a branch audit.", JO:"Works an audit team.", MID:"Audit cadet.", WO:"Ledger specialist.", NCO:"Bookkeeping supervisor.", E:"Clerk trainee." } },

judge: { tab:'gov', label:'Judiciary', name:'Constitutional Judiciary', fam:'civil',
  intro:"The Constitutional Judiciary interprets the Provincial Charter, tries civil and criminal cases and audits the legality of emergency measures. Final constitutional interpretation rests with the Supreme Commander, but day-to-day independence in civil law is guarded by statute.",
  heritage:"CIS provincial statutes and Hemes Arbora elder courts.",
  mission:"Apply the Charter and the law impartially in civil matters.",
  org:"The Constitutional Court sits above circuit courts, district courts and military tribunals.",
  chain:"Bailiff, magistrate, Associate Justice, Chief Justice, Supreme Commander on final interpretation.",
  reports:"The Constitutional Court; constitutionally subject to the Supreme Commander.",
  assets:"Court chambers and the law archive.",
  formations:["FO|Constitutional Court: the Chief Justice","FO|Circuit court: an Associate Justice or Senior Magistrate","SO|District court: a Magistrate","JO|Cases: Advocates","MID|Law cadets","WO|Court records","NCO|Order in court"],
  ranks:"-;Chief Justice;Deputy Chief Justice;Associate Justice;Senior Magistrate;Magistrate;Assistant Magistrate;Judge Advocate;Senior Advocate;Advocate;Junior Advocate;Clerk Advocate;Law Cadet;-;Chief Clerk of Court;Clerk of Court;Junior Clerk of Court;-;-;-;Chief Bailiff;Senior Bailiff;Bailiff;Junior Bailiff;-;-;-;-",
  duties:["Hear civil, criminal and administrative cases","Review the legality of orders","Advise on the Charter"],
  posts:{ FO:"Sits on the Constitutional Court.", SO:"Presides over a district court.", JO:"Prosecutes or defends cases.", MID:"Law cadet.", WO:"Manages court records.", NCO:"Keeps order in court." } },

const_: { tab:'gov', label:'Constabulary', name:'Civil Constabulary', fam:'police',
  intro:"The Civil Constabulary is the uniformed police of the civilian districts. It handles day-to-day crime, traffic and public order and refers matters of state security to the Provincial Security Bureau.",
  heritage:"Separatist district security forces.",
  mission:"Keep the peace and enforce civil law in the districts.",
  org:"District commands divide into precincts and patrol sections, with detective and traffic branches.",
  chain:"Constable, sergeant, precinct inspector, district Chief Constable, Commissioner, Minister of Justice.",
  reports:"The Ministry of Justice, with coordination from the Security Bureau.",
  assets:"Patrol speeders, precinct stations, forensic labs.",
  formations:["FO|Constabulary: the Commissioner","FO|District command: a Chief Constable","SO|Precinct: a Superintendent","JO|Patrol or detective section: an Inspector","MID|Constable cadets","WO|Forensic technicians","NCO|Station and patrol supervisors","E|Patrol constables"],
  ranks:"-;Commissioner;Deputy Commissioner;Assistant Commissioner;Chief Constable;Superintendent;Chief Inspector;Inspector;Senior Inspector;Sub-Inspector;Probationary Inspector;Junior Inspector;Constable Cadet;-;-;Master Forensic Technician;Forensic Technician;-;Constabulary Sergeant Major;-;Station Sergeant;Senior Sergeant;Sergeant;Senior Constable;Constable First Class;Constable;Probationary Constable;Constable Recruit",
  duties:["Patrol, investigate and arrest","Manage district public order","Refer security matters to the Bureau"],
  posts:{ FO:"Commands the Constabulary or a district command.", SO:"Commands a precinct.", JO:"Leads a patrol or detective section.", MID:"Constable cadet.", WO:"Forensic specialist.", NCO:"Station and patrol supervisors.", E:"Patrol constables." } },

assembly: { tab:'gov', label:'Assembly', name:'Provincial Assembly', fam:'civil',
  intro:"The Provincial Assembly is the two-chamber legislature: the elected Civilian Council for domestic law and the Military Senate for security. These are offices rather than military ranks, listed here to show how authority is arranged.",
  heritage:"The Separatist Council and Parliament.",
  mission:"Make law within the limits set by the Charter and the Supreme Commander's veto.",
  org:"Committees draft and scrutinise legislation; a joint secretariat handles records.",
  chain:"Councillors and Senators, committee chairs, Speaker, Supreme Commander (veto).",
  reports:"The electorate for the Civilian Council; the senior officer corps for the Military Senate.",
  assets:"Assembly Hall, committee rooms and the legislative record.",
  formations:["FO|Assembly: the Speaker","FO|Military Senate: its President","SO|Committees: Chairs","JO|Seats: Councillors and Senators","MID|Assembly pages","NCO|Secretariat staff"],
  ranks:"-;Speaker of the Assembly;Deputy Speaker;President of the Military Senate;Vice-President of the Senate;Chair of the Civilian Council;Committee Chair;Senior Councillor;Councillor;Senator;Junior Councillor;Assistant Councillor;Assembly Page;-;-;-;-;-;-;Clerk of the Assembly;-;Deputy Clerk;Senior Secretary;Secretary;Assistant Secretary;Junior Secretary;-;-",
  duties:["Debate and pass legislation","Scrutinise budgets and emergency measures","Confirm appointments under the Charter"],
  posts:{ FO:"Presides over a chamber.", SO:"Chairs a committee or holds a senior seat.", JO:"Sits as a councillor or senator.", MID:"Serves as a page in the chamber.", NCO:"Secretariat staff." } }
};

// TABS: the header tabs and which branch columns each one shows.
const TABS = {
  fleet:   { label:'Fleet',        cols:['navy','fighter','boarding','nint'] },
  ground:  { label:'Ground',       cols:['army','commando','pdc','aint'] },
  support: { label:'Support',      cols:['eng','log','med','rnd','sig'] },
  droid:   { label:'Droid Corps',  cols:['droid','liaison'] },
  intel:   { label:'Intel/Security', cols:['psb','veil','cry','guard','vigil'] },
  gov:     { label:'Governance',   cols:['admin','treasury','judge','const_','assembly'] }
};

// Sanity check: logs an error to the console if a branch has the wrong number of ranks, then splits ranks into arrays.
(function () {
  Object.keys(BRANCHES).forEach(k => {
    const r = BRANCHES[k].ranks.split(';');
    if (r.length !== TIERS.length) console.error('Rank count mismatch in', k, r.length);
    BRANCHES[k].ranks = r;
  });
})();
